"""sign mastery and quests

Revision ID: 222cfae098de
Revises: 6ff7d2d89b6b
Create Date: 2026-09-15 16:57:53.129613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222cfae098de'
down_revision: Union[str, Sequence[str], None] = '6ff7d2d89b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_key', sa.String(length=50), nullable=False),
    sa.Column('quest_type', sa.Enum('MISSION', 'SCENARIO', name='questtype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('prompt', sa.String(length=300), nullable=True),
    sa.Column('words_json', sa.String(length=1000), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_index'),
    sa.UniqueConstraint('quest_key')
    )
    op.create_table('user_quest_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('completed_words_json', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_id', name='uq_user_quest')
    )
    op.create_table('user_sign_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'LEARNING', 'PRACTICING', 'MASTERED', name='masterystate'), nullable=False),
    sa.Column('recognize_attempt_count', sa.Integer(), nullable=False),
    sa.Column('recognize_correct_count', sa.Integer(), nullable=False),
    sa.Column('produce_selfcheck_count', sa.Integer(), nullable=False),
    sa.Column('recall_selfcheck_count', sa.Integer(), nullable=False),
    sa.Column('distinct_days_interacted', sa.Integer(), nullable=False),
    sa.Column('last_interaction_date', sa.Date(), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='uq_user_sign_mastery_word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sign_mastery')
    op.drop_table('user_quest_progress')
    op.drop_table('quests')
    # ### end Alembic commands ###
